//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agencia()
        {
            this.ContaCorrente = new HashSet<ContaCorrente>();
        }
    
        public int ID { get; set; }
        public int Banco { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Gerente { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
    
        public virtual Banco Banco1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContaCorrente> ContaCorrente { get; set; }
    }
}
