//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FornecimentoMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FornecimentoMaterial()
        {
            this.Material = new HashSet<Material>();
        }
    
        public int Fornecedor { get; set; }
        public int Servico { get; set; }
        public System.DateTime Data { get; set; }
        public int ID { get; set; }
        public Nullable<bool> Cancelado { get; set; }
    
        public virtual Fornecedor Fornecedor1 { get; set; }
        public virtual Pagamento Pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Material { get; set; }
    }
}
