//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumSolicitacoesNaoAprovadosPorSetor
    {
        public int SetorID { get; set; }
        public string Setor { get; set; }
        public Nullable<int> NumSolicitacoes { get; set; }
        public bool Aprovado { get; set; }
    }
}
