//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelacaoFornecimento
    {
        public int FornecimentoID { get; set; }
        public string RazaoSocial { get; set; }
        public int FornecedorID { get; set; }
        public System.DateTime Data { get; set; }
        public Nullable<decimal> PrecoTotalFornecimento { get; set; }
    }
}
