//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitacaoMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitacaoMaterial()
        {
            this.Material = new HashSet<Material>();
        }
    
        public int Setor { get; set; }
        public int ID { get; set; }
        public System.DateTime Data { get; set; }
        public bool Aprovado { get; set; }
    
        public virtual Setor Setor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Material { get; set; }
    }
}
