//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfContas_a_Pagar___Web
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class ContaCorrente
    {
    	[DataMember]
        public string Conta { get; set; }
    	[DataMember]
        public int Agencia { get; set; }
    	[DataMember]
        public decimal Limite { get; set; }
    	[DataMember]
        public int Banco { get; set; }
    
        public virtual Agencia Agencia1 { get; set; }
        public virtual PlanoContas PlanoContas { get; set; }
    }
}
