//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfContas_a_Pagar___Web
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class FornecimentoServico
    {
    	[DataMember]
        public int Fornecedor { get; set; }
    	[DataMember]
        public int Servico { get; set; }
    	[DataMember]
        public System.DateTime Data { get; set; }
    	[DataMember]
        public int ID { get; set; }
    
        public virtual Fornecedor Fornecedor1 { get; set; }
        public virtual Pagamento Pagamento { get; set; }
        public virtual Servico Servico1 { get; set; }
    }
}
