//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Web___WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PesquisarCC
    {
        public string Conta { get; set; }
        public decimal Limite { get; set; }
        public string Cidade { get; set; }
        public int AgenciaID { get; set; }
        public string Email { get; set; }
        public string Endereco { get; set; }
        public string Gerente { get; set; }
        public string Telefone { get; set; }
        public string Nome { get; set; }
        public string Numero { get; set; }
    }
}
